# inpackage allows generating the mocked interfaces directly in
# the package that it mocks.
inpackage: True

# Put _mock after interface name, not after.
inpackage-suffix: True

# Use interface name in lowercase for mock file name.
case: underscore

# Prepend every mock file with _test.go. This is useful in cases
# where you are generating mocks inpackage but don't want the mocks
# to be visible to code outside of tests.
testonly: False

# Use with-expecter: True to generate EXPECT() methods for your mocks.
# This is the preferred way to setup your mocks.
with-expecter: True
keeptree: False

