name: Tests

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build -v -o . ./...

      - name: Test
        run: go test -race -v ./...
